---
name: Build

on:
  push:
  workflow_dispatch:

jobs:

  go:
    name: Go
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Build OhMyFlux
        run: |
          CGO_ENABLED=0 \
          GOOS=linux \
          GOARCH=amd64 \
          make build
